In [1]:
import numpy as np

In [2]:
def array_info(x):
    print("配列のshape", x.shape)
    print("配列の要素のデータ型", x.dtype)
    print("配列の中身\n",x,"\n")
 
a = np.arange(0, 5 )
b = np.arange(5, 10)
c = np.arange(10,20)
c = np.reshape(c, (2,5))

In [7]:
array_info(a)
array_info(b)
array_info(c)

配列のshape (5,)
配列の要素のデータ型 int64
配列の中身
 [0 1 2 3 4] 

配列のshape (5,)
配列の要素のデータ型 int64
配列の中身
 [5 6 7 8 9] 

配列のshape (2, 5)
配列の要素のデータ型 int64
配列の中身
 [[10 11 12 13 14]
 [15 16 17 18 19]] 



### 一次元配列同士の連結  

In [8]:
concat_ab = np.concatenate([a,b])
concat_ab_axis0 = np.concatenate([a,b], axis=0) # 上と同じ結果になります
 
print(concat_ab)
print(concat_ab_axis0)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


### ２次元配列同士の連結

In [11]:
a2 = a[None,:]
b2 = b[None,:]
 
array_info(a2)
array_info(b2)
print('a2.shape = ', a2.shape) # (1, 5)
print('b2.shape = ', b2.shape) # (1, 5)

配列のshape (1, 5)
配列の要素のデータ型 int64
配列の中身
 [[0 1 2 3 4]] 

配列のshape (1, 5)
配列の要素のデータ型 int64
配列の中身
 [[5 6 7 8 9]] 

a2.shape =  (1, 5)
b2.shape =  (1, 5)


In [12]:
concat_a2b2_axis0 = np.concatenate([a2,b2], axis=0)
concat_a2b2_axis1 = np.concatenate([a2,b2,a2], axis=1)
 
array_info(concat_a2b2_axis0)
array_info(concat_a2b2_axis1)

配列のshape (2, 5)
配列の要素のデータ型 int64
配列の中身
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

配列のshape (1, 15)
配列の要素のデータ型 int64
配列の中身
 [[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4]] 



In [14]:
# axisに指定した軸方向に新しい要素を追加するため、axisによっては配列の形状が噛み合わないとエラーが発生します。
np.concatenate([a2,c], axis=0)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
np.concatenate([a2,c], axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly